# Generated by Django 3.1.2 on 2021-11-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0002_auto_20211102_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='画像'),
        ),
    ]
